/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=social-media/wrangler.jsonc --include-runtime=false social-media/worker-configuration.d.ts` (hash: 7a73ca0061acacbbebe9ae5e65dca6b1)
interface __BaseEnv_Env {
	IMAGES: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./media-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
